# Generated by Django 6.0.6 on 2026-07-08 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='fee',
            field=models.CharField(default='Free', max_length=50),
        ),
        migrations.AddField(
            model_name='club',
            name='memberCount',
            field=models.IntegerField(default=0),
        ),
    ]
