# Generated by Django 6.0.6 on 2026-07-08 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_club_fee_club_membercount'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='founded',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='club',
            name='full_description',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='club',
            name='objectives',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='club',
            name='president',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='club',
            name='requirements',
            field=models.TextField(default=''),
        ),
    ]
