# Generated by Django 6.0.6 on 2026-07-14 13:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_club_founded_club_full_description_club_objectives_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Application',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Rejected', 'Rejected')], default='Pending', max_length=20)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.club')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.student')),
            ],
            options={
                'unique_together': {('student', 'club')},
            },
        ),
    ]
